### ISSUE TITLE
Cant create capstone not found

### ISSUE THREAD

**Issue by gdomod** [stevemk14ebr/BF4-AtomBot#1]
Hey i want a little play with your nice skeleton.

But if i want to create (i allready set the general linker options to yes) i got a error cannot find capstone.lib 

can u help me please

**Comment by stevemk14ebr** [comment]
You need to build capstone, which can be found on my github. Creating an issue on github is not the proper way to get support. Also note that this is out of date and you will need to align the classes to the current update of BF4 or this will crash.
